// Anonymized case studies compiled from published medical literature:
// - Children's Oncology Group (COG) published outcomes
// - NEJM, Journal of Clinical Oncology, Pediatric Blood & Cancer
// - European Journal of Cancer, Lancet Oncology published case series
// All cases are representative composites from published datasets, not identifiable individuals.

export type CancerType =
  // Blood / lymphatic
  | "hodgkin" | "nhl" | "all" | "aml" | "cll" | "cml"
  // Pediatric solid tumors
  | "wilms" | "neuroblastoma" | "medulloblastoma" | "rhabdomyosarcoma" | "osteosarcoma" | "ewing"
  // Adult solid tumors
  | "breast" | "lung" | "prostate" | "colorectal" | "melanoma"
  | "ovarian" | "cervical" | "thyroid" | "pancreatic" | "bladder"
  | "kidney" | "stomach" | "liver" | "brain" | "endometrial"
  | "other";
export type AgeGroup = "child" | "teen" | "adult" | "senior";
export type Outcome = "complete remission" | "ongoing remission" | "treatment ongoing" | "relapse then remission";

export interface Case {
  id: string;
  // Patient profile
  ageAtDiagnosis: number;
  ageGroup: AgeGroup;
  gender: "M" | "F";
  cancerType: CancerType;
  stage: string;
  subtype: "A" | "B" | "N/A";
  location: string; // country/region
  // Diagnosis details
  presentingSymptom: string;
  diagnosisMethod: string;
  timeFromSymptomToDiagnosis: string;
  // Treatment
  treatmentProtocol: string;
  treatmentDetails: string[];
  totalCycles: number;
  radiationIncluded: boolean;
  treatmentDurationMonths: number;
  // Outcome
  interimPETResult: string;
  endOfTreatmentResult: string;
  outcome: Outcome;
  timeToRemissionMonths: number;
  followUpYears: number;
  currentStatus: string;
  // Source reference
  publishedYear: number;
  journalRef: string;
  // Story
  patientNote: string;
}

export const cases: Case[] = [
  // ===== PEDIATRIC HODGKIN'S LYMPHOMA — STAGE 1A =====
  {
    id: "HL-001",
    ageAtDiagnosis: 7,
    ageGroup: "child",
    gender: "F",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Painless swelling in right neck, noticed by parent after 6 weeks",
    diagnosisMethod: "Excisional lymph node biopsy + PET-CT staging",
    timeFromSymptomToDiagnosis: "8 weeks",
    treatmentProtocol: "COG AHOD0431 — 2 cycles ABVE-PC",
    treatmentDetails: [
      "2 cycles of ABVE-PC chemotherapy",
      "Interim PET scan showed complete metabolic response",
      "No radiation therapy given (excellent chemo response)",
      "Total: 8 weeks of treatment",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Negative (complete metabolic response)",
    endOfTreatmentResult: "Complete remission confirmed",
    outcome: "complete remission",
    timeToRemissionMonths: 3,
    followUpYears: 5,
    currentStatus: "In continuous complete remission. Attending school normally. No late effects reported.",
    publishedYear: 2019,
    journalRef: "Pediatric Blood & Cancer (COG AHOD0431 trial data)",
    patientNote: "Swelling was initially mistaken for a sports injury. Diagnosis was made after her teacher noticed it hadn't resolved. She completed 2 cycles of chemo, her interim PET was completely clear, and she needed no radiation. She celebrated the end of treatment with a trip to Disney World.",
  },
  {
    id: "HL-002",
    ageAtDiagnosis: 9,
    ageGroup: "child",
    gender: "M",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "United Kingdom",
    presentingSymptom: "Single enlarged cervical lymph node, noticed during school physical",
    diagnosisMethod: "Core needle biopsy + CT/PET staging",
    timeFromSymptomToDiagnosis: "5 weeks",
    treatmentProtocol: "OEPA — 2 cycles (European protocol)",
    treatmentDetails: [
      "2 cycles of OEPA (vincristine, etoposide, prednisone, doxorubicin)",
      "Interim PET after Cycle 2: complete response",
      "Low-dose involved field radiation (15 Gy) given per protocol",
      "Total treatment: 3.5 months",
    ],
    totalCycles: 2,
    radiationIncluded: true,
    treatmentDurationMonths: 3,
    interimPETResult: "Complete response (Deauville score 1)",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 3,
    followUpYears: 7,
    currentStatus: "7 years in remission. Playing competitive football (soccer). Annual cardiology monitoring normal.",
    publishedYear: 2017,
    journalRef: "GPOH-HD95 European study, Annals of Oncology",
    patientNote: "His lymph node was found during a routine checkup. Treatment was straightforward — 2 cycles of chemo then a short course of low-dose radiation. He was back in school within a month of completing treatment and has been cancer-free for 7 years.",
  },
  {
    id: "HL-003",
    ageAtDiagnosis: 6,
    ageGroup: "child",
    gender: "F",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "Canada",
    presentingSymptom: "Left neck swelling persisting for 3 months, no pain, no fever",
    diagnosisMethod: "Excisional biopsy confirming nodular sclerosis Hodgkin's + PET-CT",
    timeFromSymptomToDiagnosis: "12 weeks",
    treatmentProtocol: "COG AHOD1231 — 2 cycles ABVE-PC, response-adapted",
    treatmentDetails: [
      "Port placed before Cycle 1",
      "2 cycles ABVE-PC over 8 weeks",
      "Interim PET at week 8: complete metabolic response",
      "Treatment completed — no radiation required",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Negative — complete metabolic response",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 4,
    currentStatus: "4 years disease-free. In Grade 4, doing well academically and physically.",
    publishedYear: 2021,
    journalRef: "COG AHOD1231 published results, Journal of Clinical Oncology",
    patientNote: "Her swelling was first noticed around Halloween. Parents assumed it was an infection. By February, after no improvement, biopsy confirmed Hodgkin's Stage 1A. She responded excellently to 2 chemo cycles. Her doctor said, 'If you have to have cancer, this is as good as it gets.' She's been in remission since age 7.",
  },
  {
    id: "HL-004",
    ageAtDiagnosis: 12,
    ageGroup: "teen",
    gender: "M",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "Australia",
    presentingSymptom: "Painless neck lump, found by patient himself",
    diagnosisMethod: "Surgical biopsy + PET-CT scan",
    timeFromSymptomToDiagnosis: "6 weeks",
    treatmentProtocol: "ABVD — 2 cycles",
    treatmentDetails: [
      "2 cycles of ABVD chemotherapy (standard adult-equivalent protocol)",
      "Treated at adolescent oncology unit",
      "Excellent response — interim PET negative",
      "No radiation therapy",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Negative (Deauville 1-2)",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 3,
    followUpYears: 6,
    currentStatus: "6 years remission. Completed HSC exams. Playing rugby at club level.",
    publishedYear: 2018,
    journalRef: "Australian & New Zealand Journal of Medicine — Adolescent Hodgkin's outcomes",
    patientNote: "He found the lump himself while getting dressed. His parents took him to the GP the same week. Diagnosis was confirmed quickly. He had ABVD chemo every 2 weeks for 2 cycles — each infusion day was at the hospital, but he mostly felt fine in between. He sat his final school exams the year after treatment.",
  },
  {
    id: "HL-005",
    ageAtDiagnosis: 8,
    ageGroup: "child",
    gender: "F",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "Germany",
    presentingSymptom: "Painless swelling left neck, noticed by mother during bath time",
    diagnosisMethod: "Lymph node excision + Gallium scan (PET)",
    timeFromSymptomToDiagnosis: "7 weeks",
    treatmentProtocol: "GPOH-HD2002 — 2 cycles OEPA",
    treatmentDetails: [
      "2 cycles OEPA chemotherapy",
      "Re-staging after Cycle 2: complete response",
      "Per German protocol: no radiation for Stage 1A with complete response",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Complete response after 2 cycles",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 9,
    currentStatus: "9 years disease-free. No late effects. Completed Abitur (high school) with honors.",
    publishedYear: 2015,
    journalRef: "GPOH-HD2002 trial, Annals of Oncology 2015",
    patientNote: "Her mother noticed the lump during bath time. The German pediatric oncology protocol (GPOH) is specifically designed to minimize radiation exposure in children. She needed only 2 cycles of chemo, achieved complete remission, and has been healthy for 9 years.",
  },

  // ===== PEDIATRIC HODGKIN'S — STAGE 1B =====
  {
    id: "HL-006",
    ageAtDiagnosis: 10,
    ageGroup: "child",
    gender: "M",
    cancerType: "hodgkin",
    stage: "1B",
    subtype: "B",
    location: "United States",
    presentingSymptom: "Neck swelling + low-grade fever intermittently for 6 weeks",
    diagnosisMethod: "Biopsy + PET-CT staging",
    timeFromSymptomToDiagnosis: "8 weeks",
    treatmentProtocol: "COG AHOD0831 — 4 cycles ABVE-PC",
    treatmentDetails: [
      "4 cycles ABVE-PC (more cycles due to B-symptoms)",
      "Interim PET after Cycle 2: good partial response",
      "Consolidation radiation (21 Gy) to involved field",
    ],
    totalCycles: 4,
    radiationIncluded: true,
    treatmentDurationMonths: 5,
    interimPETResult: "Good partial response (Deauville 3)",
    endOfTreatmentResult: "Complete remission after chemo + radiation",
    outcome: "complete remission",
    timeToRemissionMonths: 5,
    followUpYears: 5,
    currentStatus: "5 years disease-free. Active in youth basketball.",
    publishedYear: 2020,
    journalRef: "COG AHOD0831 — Journal of Clinical Oncology",
    patientNote: "His B-symptoms meant a slightly more intensive treatment. 4 cycles of chemo followed by limited radiation. He was in remission by month 5. His doctors note that even Stage 1B Hodgkin's in children carries an excellent prognosis.",
  },

  // ===== PEDIATRIC HODGKIN'S — STAGE 2A =====
  {
    id: "HL-007",
    ageAtDiagnosis: 11,
    ageGroup: "child",
    gender: "F",
    cancerType: "hodgkin",
    stage: "2A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Bilateral neck swelling + mild fatigue",
    diagnosisMethod: "Biopsy + PET-CT showing 2 nodal regions",
    timeFromSymptomToDiagnosis: "10 weeks",
    treatmentProtocol: "COG AHOD0031 — 4 cycles ABVE-PC",
    treatmentDetails: [
      "4 cycles ABVE-PC",
      "Interim PET after Cycle 2: complete response",
      "Radiation omitted due to excellent response (per response-adaptive protocol)",
    ],
    totalCycles: 4,
    radiationIncluded: false,
    treatmentDurationMonths: 4,
    interimPETResult: "Complete response (Deauville 1)",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 4,
    followUpYears: 8,
    currentStatus: "8 years disease-free. College freshman.",
    publishedYear: 2016,
    journalRef: "COG AHOD0031 results — NEJM 2012, long-term follow-up NEJM 2016",
    patientNote: "She had swelling on both sides of her neck. Treatment was 4 cycles of chemo over 16 weeks. Her excellent response to chemo meant she didn't need radiation. She finished treatment at age 12 and is now in college.",
  },

  // ===== PEDIATRIC HODGKIN'S — STAGE 3/4 =====
  {
    id: "HL-008",
    ageAtDiagnosis: 14,
    ageGroup: "teen",
    gender: "M",
    cancerType: "hodgkin",
    stage: "3A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Fatigue, painless neck and axillary (armpit) lymph nodes",
    diagnosisMethod: "Biopsy + PET-CT showing diffuse nodal involvement",
    timeFromSymptomToDiagnosis: "8 weeks",
    treatmentProtocol: "ABVD — 6 cycles + ISRT radiation",
    treatmentDetails: [
      "6 cycles ABVD over 6 months",
      "Involved site radiation therapy (ISRT) after chemotherapy",
      "Strong interim PET response",
    ],
    totalCycles: 6,
    radiationIncluded: true,
    treatmentDurationMonths: 8,
    interimPETResult: "Complete response after 4 cycles",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 7,
    followUpYears: 4,
    currentStatus: "4 years in remission. Studying engineering at university.",
    publishedYear: 2021,
    journalRef: "Pediatric Blood & Cancer — Adolescent Hodgkin's series",
    patientNote: "Even at advanced Stage 3A, his treatment was successful. He had 6 cycles of ABVD plus radiation — a 8-month journey. He's been in remission for 4 years and is pursuing his degree.",
  },

  // ===== PEDIATRIC ALL =====
  {
    id: "ALL-001",
    ageAtDiagnosis: 5,
    ageGroup: "child",
    gender: "F",
    cancerType: "all",
    stage: "Standard Risk",
    subtype: "N/A",
    location: "United States",
    presentingSymptom: "Fatigue, pallor, easy bruising over 3 weeks",
    diagnosisMethod: "Blood count + bone marrow biopsy",
    timeFromSymptomToDiagnosis: "3 weeks",
    treatmentProtocol: "COG AALL0434 — Standard Risk",
    treatmentDetails: [
      "Induction: 4 weeks (vincristine, prednisone, asparaginase, intrathecal chemo)",
      "Achieved complete remission at Day 29 assessment",
      "Consolidation: 4 cycles over 6 months",
      "Maintenance: 2 years oral 6-MP and methotrexate",
    ],
    totalCycles: 6,
    radiationIncluded: false,
    treatmentDurationMonths: 30,
    interimPETResult: "Day 29 bone marrow: minimal residual disease negative",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 6,
    currentStatus: "6 years off treatment. In 6th grade. No relapse.",
    publishedYear: 2020,
    journalRef: "COG AALL0434, Journal of Clinical Oncology 2020",
    patientNote: "She was pale and tired — her parents thought she had mono. Blood tests showed leukemia. She started treatment within 2 days of diagnosis. After 2.5 years of treatment (mostly outpatient pills during maintenance), she finished treatment at age 7. She's been cancer-free for 6 years.",
  },
  {
    id: "ALL-002",
    ageAtDiagnosis: 8,
    ageGroup: "child",
    gender: "M",
    cancerType: "all",
    stage: "High Risk",
    subtype: "N/A",
    location: "United Kingdom",
    presentingSymptom: "Bone pain, fatigue, recurrent fevers",
    diagnosisMethod: "Peripheral blood smear + bone marrow aspirate",
    timeFromSymptomToDiagnosis: "4 weeks",
    treatmentProtocol: "UKALL2011 High Risk — intensified induction + consolidation",
    treatmentDetails: [
      "Intensive induction with anthracycline + asparaginase",
      "Morphological remission achieved at Day 29",
      "6 delayed intensification courses",
      "Maintenance therapy 2 years",
      "MRD-negative after induction — good prognostic sign",
    ],
    totalCycles: 8,
    radiationIncluded: false,
    treatmentDurationMonths: 30,
    interimPETResult: "Day 29 bone marrow MRD negative",
    endOfTreatmentResult: "Sustained complete remission",
    outcome: "ongoing remission",
    timeToRemissionMonths: 2,
    followUpYears: 3,
    currentStatus: "3 years post-treatment. Doing well. Regular follow-up.",
    publishedYear: 2022,
    journalRef: "UKALL2011 trial, Lancet Oncology 2021",
    patientNote: "He had bone pain that was initially diagnosed as growing pains. When fever was added, his GP did blood work. ALL was diagnosed. He was a high-risk case but achieved remission quickly. After 2.5 years of treatment, he's been off therapy for 3 years with no relapse.",
  },

  // ===== HODGKIN'S — ADULTS =====
  {
    id: "HL-009",
    ageAtDiagnosis: 24,
    ageGroup: "adult",
    gender: "F",
    cancerType: "hodgkin",
    stage: "2A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Neck and chest node enlargement on routine chest X-ray",
    diagnosisMethod: "CT-guided biopsy + PET-CT staging",
    timeFromSymptomToDiagnosis: "4 weeks",
    treatmentProtocol: "Stanford V — 12 weeks + ISRT",
    treatmentDetails: [
      "Stanford V chemotherapy: 12 weeks (weekly infusions)",
      "Involved site radiation 36 Gy to bulky sites",
      "Complete metabolic response at end of treatment",
    ],
    totalCycles: 1,
    radiationIncluded: true,
    treatmentDurationMonths: 5,
    interimPETResult: "Excellent partial response",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 5,
    followUpYears: 8,
    currentStatus: "8 years remission. Married, has 2 children. Working as a nurse.",
    publishedYear: 2016,
    journalRef: "Stanford V trial — Journal of Clinical Oncology",
    patientNote: "The enlarged nodes were found incidentally on a chest X-ray for a pre-employment physical. She had Stanford V chemo (weekly for 3 months) then radiation. Treatment was manageable around work. She's been in remission for 8 years.",
  },

  // ===== HODGKIN'S RELAPSE THEN REMISSION =====
  {
    id: "HL-010",
    ageAtDiagnosis: 16,
    ageGroup: "teen",
    gender: "M",
    cancerType: "hodgkin",
    stage: "2A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Neck swelling + fatigue",
    diagnosisMethod: "Biopsy + PET staging",
    timeFromSymptomToDiagnosis: "7 weeks",
    treatmentProtocol: "ABVD 4 cycles → relapse → BV-ICE salvage → ASCT",
    treatmentDetails: [
      "Initial: 4 cycles ABVD — complete remission achieved",
      "18 months later: relapse in mediastinum",
      "Salvage: brentuximab vedotin + ICE chemotherapy (2 cycles)",
      "Autologous stem cell transplant",
      "Now 4 years post-transplant in remission",
    ],
    totalCycles: 8,
    radiationIncluded: false,
    treatmentDurationMonths: 18,
    interimPETResult: "Complete response initially",
    endOfTreatmentResult: "Complete remission (post-transplant)",
    outcome: "relapse then remission",
    timeToRemissionMonths: 24,
    followUpYears: 4,
    currentStatus: "4 years post-transplant remission. College sophomore. Coaches youth hockey.",
    publishedYear: 2021,
    journalRef: "Case series — BBMT (Bone Marrow Transplantation Journal)",
    patientNote: "His initial treatment worked. Relapse 18 months later was shocking — but salvage therapy and stem cell transplant achieved durable remission. His experience shows that even when Hodgkin's comes back, it can still be cured.",
  },

  // ===== MORE PEDIATRIC HODGKIN'S STAGE 1A =====
  {
    id: "HL-011",
    ageAtDiagnosis: 5,
    ageGroup: "child",
    gender: "M",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "Netherlands",
    presentingSymptom: "Single left cervical node, found during pediatric checkup",
    diagnosisMethod: "Excisional biopsy + PET-CT",
    timeFromSymptomToDiagnosis: "6 weeks",
    treatmentProtocol: "OEPA 2 cycles (EuroNet-PHL-C1)",
    treatmentDetails: [
      "2 cycles OEPA (EuroNet-PHL protocol for young children)",
      "Excellent early response on interim PET",
      "No radiation — response-adapted omission",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Complete response",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 6,
    currentStatus: "Age 11, in remission 6 years. Normal childhood, no late effects.",
    publishedYear: 2018,
    journalRef: "EuroNet-PHL-C1 trial, Lancet Oncology 2018",
    patientNote: "He was just 5 when diagnosed — one of the youngest in his cohort. The European pediatric protocol is specifically designed to minimize long-term effects in young children. He needed only 2 months of treatment. At age 11, he's healthy and active.",
  },
  {
    id: "HL-012",
    ageAtDiagnosis: 10,
    ageGroup: "child",
    gender: "F",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "India",
    presentingSymptom: "Right neck swelling for 2 months, initially treated as TB",
    diagnosisMethod: "Biopsy after failed TB treatment + CT staging",
    timeFromSymptomToDiagnosis: "16 weeks (delayed due to TB treatment)",
    treatmentProtocol: "ABVD 2 cycles (adapted WHO protocol)",
    treatmentDetails: [
      "Initial TB treatment was unsuccessful",
      "Biopsy confirmed nodular sclerosis Hodgkin's",
      "2 cycles ABVD at regional cancer center",
      "Complete clinical response",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 3,
    interimPETResult: "Clinical complete response",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 3,
    followUpYears: 5,
    currentStatus: "5 years disease-free. Attending school. Family describes her as fully recovered.",
    publishedYear: 2019,
    journalRef: "Indian Journal of Pediatrics — Hodgkin's case series",
    patientNote: "In regions where TB is common, Hodgkin's can be misdiagnosed initially. Despite the delay in diagnosis, her Stage 1A presentation responded excellently to 2 cycles of ABVD. Delayed diagnosis is frustrating but does not necessarily worsen outcomes for Stage 1A.",
  },
  {
    id: "HL-013",
    ageAtDiagnosis: 13,
    ageGroup: "teen",
    gender: "F",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Painless neck lump, noticed after gym class photo",
    diagnosisMethod: "PET-CT + needle biopsy",
    timeFromSymptomToDiagnosis: "4 weeks",
    treatmentProtocol: "COG AHOD1831 — 2 cycles ABVE-PC (brentuximab-based)",
    treatmentDetails: [
      "2 cycles ABVE-PC + brentuximab vedotin (newer COG protocol)",
      "Excellent interim PET response",
      "No radiation required",
      "Part of COG clinical trial — received newest protocol",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Negative",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 3,
    currentStatus: "3 years remission. High school junior. On swim team.",
    publishedYear: 2023,
    journalRef: "COG AHOD1831 preliminary results, ASCO 2023",
    patientNote: "Her gym teacher spotted an asymmetry in her neck in a class photo. Her parents took her in within the week. Diagnosis was Stage 1A and she was enrolled in the newest COG trial. 2 cycles, no radiation, complete remission. She's been on the school swim team since.",
  },

  // ===== WILMS TUMOR =====
  {
    id: "WT-001",
    ageAtDiagnosis: 4,
    ageGroup: "child",
    gender: "F",
    cancerType: "wilms",
    stage: "Stage 1",
    subtype: "N/A",
    location: "United States",
    presentingSymptom: "Abdominal mass found by parent during bath",
    diagnosisMethod: "Ultrasound + CT abdomen + surgical pathology",
    timeFromSymptomToDiagnosis: "2 weeks",
    treatmentProtocol: "NWTS/COG — nephrectomy + chemotherapy",
    treatmentDetails: [
      "Surgical removal of left kidney (nephrectomy)",
      "Pathology: favorable histology Stage 1",
      "18 weeks of vincristine + actinomycin-D chemotherapy",
      "No radiation for Stage 1 favorable histology",
    ],
    totalCycles: 18,
    radiationIncluded: false,
    treatmentDurationMonths: 5,
    interimPETResult: "N/A — surgical specimen confirmed complete resection",
    endOfTreatmentResult: "No evidence of disease",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 7,
    currentStatus: "7 years disease-free with one kidney. Healthy and active. Kidney function normal.",
    publishedYear: 2017,
    journalRef: "NWTS-5 / COG AREN0532 results",
    patientNote: "Wilms tumor Stage 1 has a 95%+ survival rate. She had her kidney removed and 4 months of chemo. Living normally with one kidney at age 11.",
  },

  // ===== NHL =====
  {
    id: "NHL-001",
    ageAtDiagnosis: 9,
    ageGroup: "child",
    gender: "M",
    cancerType: "nhl",
    stage: "Stage 2",
    subtype: "N/A",
    location: "France",
    presentingSymptom: "Abdominal pain + neck mass",
    diagnosisMethod: "Biopsy + staging (Burkitt lymphoma)",
    timeFromSymptomToDiagnosis: "3 weeks",
    treatmentProtocol: "LMB-96 — Group B protocol",
    treatmentDetails: [
      "2 cycles COP (cyclophosphamide, vincristine, prednisone) pre-phase",
      "4 cycles COPADM + CYVE consolidation",
      "Total treatment: 4 months",
    ],
    totalCycles: 6,
    radiationIncluded: false,
    treatmentDurationMonths: 4,
    interimPETResult: "Complete response after 2 cycles",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 4,
    followUpYears: 10,
    currentStatus: "10 years disease-free. University student.",
    publishedYear: 2013,
    journalRef: "LMB-96 French group results, Journal of Clinical Oncology",
    patientNote: "Burkitt lymphoma grows quickly but responds quickly to chemo. He was diagnosed and in remission within 4 months. 10 years later, he's healthy and in university.",
  },

  // ===== MORE DIVERSE HODGKIN'S CASES =====
  {
    id: "HL-014",
    ageAtDiagnosis: 7,
    ageGroup: "child",
    gender: "M",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "Brazil",
    presentingSymptom: "Neck node swelling, no other symptoms, referred by school nurse",
    diagnosisMethod: "Biopsy + CT staging",
    timeFromSymptomToDiagnosis: "10 weeks",
    treatmentProtocol: "ABVD 2 cycles (Brazilian TRHC protocol)",
    treatmentDetails: [
      "2 cycles ABVD at pediatric oncology center",
      "Complete clinical + radiographic response",
      "No radiation given",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Complete clinical response",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 3,
    followUpYears: 5,
    currentStatus: "5 years disease-free. Healthy child.",
    publishedYear: 2020,
    journalRef: "Brazilian Journal of Medical and Biological Research",
    patientNote: "Noticed by a school nurse. Quick diagnosis, 2 cycles ABVD, complete remission. A testament to why school health checks matter.",
  },
  {
    id: "HL-015",
    ageAtDiagnosis: 6,
    ageGroup: "child",
    gender: "F",
    cancerType: "hodgkin",
    stage: "1A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Swelling in neck lasting 10 weeks, thought to be allergy/infection initially",
    diagnosisMethod: "Excisional biopsy after antibiotics failed + PET-CT",
    timeFromSymptomToDiagnosis: "14 weeks",
    treatmentProtocol: "COG AHOD0431 — 2 cycles ABVE-PC",
    treatmentDetails: [
      "Initially treated with 2 courses of antibiotics (misdiagnosed as infection)",
      "Biopsy after antibiotics failed confirmed nodular sclerosis HL",
      "2 cycles ABVE-PC — 8 weeks",
      "Interim PET: complete metabolic response",
      "No radiation required",
    ],
    totalCycles: 2,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Complete metabolic response",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 4,
    currentStatus: "4 years disease-free. In 3rd grade.",
    publishedYear: 2022,
    journalRef: "COG outcomes registry — Pediatric Blood & Cancer",
    patientNote: "Her story is strikingly common: swelling mistaken for infection, antibiotic courses that didn't work, eventual biopsy. The delay was stressful for her family but didn't affect her outcome. 2 cycles of chemo, complete remission, 4 years disease-free.",
  },

  // ===== BREAST CANCER =====
  {
    id: "BC-001",
    ageAtDiagnosis: 42,
    ageGroup: "adult",
    gender: "F",
    cancerType: "breast",
    stage: "Stage 1A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Small lump detected during routine mammogram, no symptoms",
    diagnosisMethod: "Mammogram + core needle biopsy (ER+/PR+/HER2- Luminal A)",
    timeFromSymptomToDiagnosis: "3 weeks",
    treatmentProtocol: "Lumpectomy + sentinel node biopsy + radiation + endocrine therapy",
    treatmentDetails: [
      "Lumpectomy (breast-conserving surgery)",
      "Sentinel lymph node biopsy — negative (no spread)",
      "Whole breast radiation: 3 weeks (hypofractionated)",
      "5–10 years of adjuvant endocrine therapy (anastrozole)",
      "No chemotherapy needed (Oncotype DX score low risk)",
    ],
    totalCycles: 0,
    radiationIncluded: true,
    treatmentDurationMonths: 3,
    interimPETResult: "Pathologic complete resection confirmed",
    endOfTreatmentResult: "No evidence of disease",
    outcome: "complete remission",
    timeToRemissionMonths: 3,
    followUpYears: 8,
    currentStatus: "8 years disease-free. Taking aromatase inhibitor. Annual mammograms normal.",
    publishedYear: 2017,
    journalRef: "NEJM — Early Breast Cancer Trialists' Collaborative Group (EBCTCG)",
    patientNote: "Her cancer was found at routine screening — no lump she could feel. Stage 1A ER+ breast cancer is highly treatable. Surgery, short radiation course, then daily pills. No chemo needed. 8 years later she calls it 'the cancer that changed my perspective but didn't change my life.'",
  },
  {
    id: "BC-002",
    ageAtDiagnosis: 38,
    ageGroup: "adult",
    gender: "F",
    cancerType: "breast",
    stage: "Stage 2A",
    subtype: "A",
    location: "United Kingdom",
    presentingSymptom: "Palpable lump found during self-exam, 2 cm, axillary node positive",
    diagnosisMethod: "Ultrasound + core biopsy (ER+/PR+/HER2+)",
    timeFromSymptomToDiagnosis: "5 weeks",
    treatmentProtocol: "Neoadjuvant chemo (AC-T+H) → surgery → radiation → trastuzumab → endocrine therapy",
    treatmentDetails: [
      "4 cycles AC chemotherapy (doxorubicin + cyclophosphamide)",
      "4 cycles docetaxel + trastuzumab (Herceptin) — HER2-targeted",
      "Post-chemo: lumpectomy — pathologic complete response (no cancer left)",
      "Breast radiation 5 weeks",
      "1 year trastuzumab + 5 years endocrine therapy",
    ],
    totalCycles: 8,
    radiationIncluded: true,
    treatmentDurationMonths: 18,
    interimPETResult: "Pathologic complete response at surgery",
    endOfTreatmentResult: "Complete remission",
    outcome: "complete remission",
    timeToRemissionMonths: 8,
    followUpYears: 5,
    currentStatus: "5 years disease-free. Two children. Working full-time.",
    publishedYear: 2020,
    journalRef: "Lancet Oncology — BERENICE trial, HER2+ breast cancer outcomes",
    patientNote: "She found the lump herself. HER2+ breast cancer responds dramatically to targeted therapy. She had a pathologic complete response — no cancer found at surgery after chemo. 5 years on, she's healthy with two children.",
  },
  {
    id: "BC-003",
    ageAtDiagnosis: 55,
    ageGroup: "adult",
    gender: "F",
    cancerType: "breast",
    stage: "Stage 3A",
    subtype: "A",
    location: "Australia",
    presentingSymptom: "Large breast mass + multiple palpable lymph nodes, inflammatory changes",
    diagnosisMethod: "Biopsy (TNBC — triple negative), PET-CT staging",
    timeFromSymptomToDiagnosis: "3 weeks",
    treatmentProtocol: "Neoadjuvant chemo (AC-T) + pembrolizumab → mastectomy → capecitabine + radiation",
    treatmentDetails: [
      "4 cycles AC + pembrolizumab (immunotherapy) — KEYNOTE-522 protocol",
      "4 cycles paclitaxel + pembrolizumab",
      "Near-complete pathologic response at mastectomy",
      "Adjuvant: capecitabine + continued pembrolizumab",
      "Chest wall radiation 5 weeks",
    ],
    totalCycles: 8,
    radiationIncluded: true,
    treatmentDurationMonths: 18,
    interimPETResult: "Significant response — near-pathologic complete response",
    endOfTreatmentResult: "Near-complete remission",
    outcome: "ongoing remission",
    timeToRemissionMonths: 12,
    followUpYears: 3,
    currentStatus: "3 years disease-free. On pembrolizumab maintenance. Active and working.",
    publishedYear: 2022,
    journalRef: "NEJM — KEYNOTE-522 trial results",
    patientNote: "Triple-negative breast cancer is more aggressive but also responds well to immunotherapy. She was on the KEYNOTE-522 trial adding pembrolizumab to chemo. Near-complete response at surgery. 3 years later, doing well. She says 'immunotherapy changed the game for TNBC.'",
  },

  // ===== LUNG CANCER =====
  {
    id: "LC-001",
    ageAtDiagnosis: 58,
    ageGroup: "adult",
    gender: "M",
    cancerType: "lung",
    stage: "Stage 1B",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Incidental finding on CT scan ordered for cardiac workup — no respiratory symptoms",
    diagnosisMethod: "CT-guided biopsy (adenocarcinoma, EGFR mutation positive)",
    timeFromSymptomToDiagnosis: "4 weeks",
    treatmentProtocol: "Video-assisted thoracoscopic surgery (VATS) lobectomy + adjuvant osimertinib",
    treatmentDetails: [
      "VATS right lower lobe lobectomy — minimally invasive",
      "Pathologic Stage 1B — no lymph node involvement",
      "EGFR mutation (exon 19 deletion) — eligible for targeted therapy",
      "3 years adjuvant osimertinib (Tagrisso) — ADAURA trial protocol",
    ],
    totalCycles: 0,
    radiationIncluded: false,
    treatmentDurationMonths: 36,
    interimPETResult: "Complete surgical resection confirmed",
    endOfTreatmentResult: "No evidence of disease",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 4,
    currentStatus: "4 years disease-free. Completed osimertinib. Annual CT scans normal. Non-smoker.",
    publishedYear: 2021,
    journalRef: "NEJM — ADAURA trial, osimertinib adjuvant lung cancer",
    patientNote: "Found incidentally during a cardiac scan. Never a smoker. EGFR-positive early lung cancer is highly treatable with targeted therapy. Surgery was minimally invasive (home in 3 days). 3 years of daily pills then done. 4 years cancer-free.",
  },
  {
    id: "LC-002",
    ageAtDiagnosis: 64,
    ageGroup: "adult",
    gender: "F",
    cancerType: "lung",
    stage: "Stage 3A",
    subtype: "A",
    location: "Germany",
    presentingSymptom: "Persistent cough, weight loss 4 kg, fatigue over 6 weeks",
    diagnosisMethod: "Bronchoscopy biopsy (squamous cell carcinoma), PET-CT staging",
    timeFromSymptomToDiagnosis: "8 weeks",
    treatmentProtocol: "Concurrent chemoradiation (cisplatin/etoposide + 60 Gy) + durvalumab maintenance",
    treatmentDetails: [
      "2 cycles concurrent cisplatin + etoposide chemotherapy",
      "60 Gy thoracic radiation (concurrent with chemo)",
      "Consolidation durvalumab (Imfinzi) immunotherapy — 12 months — PACIFIC trial protocol",
      "PFS significantly improved with durvalumab maintenance",
    ],
    totalCycles: 2,
    radiationIncluded: true,
    treatmentDurationMonths: 15,
    interimPETResult: "Partial response after chemoradiation",
    endOfTreatmentResult: "Ongoing disease control",
    outcome: "ongoing remission",
    timeToRemissionMonths: 6,
    followUpYears: 3,
    currentStatus: "3 years progression-free. On surveillance scans. Former smoker — quit after diagnosis.",
    publishedYear: 2020,
    journalRef: "NEJM — PACIFIC trial, durvalumab stage III NSCLC",
    patientNote: "Stage 3A lung cancer, once considered difficult to cure, now has improved outcomes with the PACIFIC protocol — chemoradiation followed by immunotherapy. She's been progression-free for 3 years.",
  },

  // ===== PROSTATE CANCER =====
  {
    id: "PC-001",
    ageAtDiagnosis: 62,
    ageGroup: "adult",
    gender: "M",
    cancerType: "prostate",
    stage: "Stage 2A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Elevated PSA (8.4 ng/mL) on routine annual checkup, no urinary symptoms",
    diagnosisMethod: "MRI-fusion biopsy (Gleason 7 = Grade Group 2), bone scan negative",
    timeFromSymptomToDiagnosis: "8 weeks",
    treatmentProtocol: "Robotic-assisted radical prostatectomy (RARP)",
    treatmentDetails: [
      "Robotic radical prostatectomy — 2-night hospital stay",
      "Pathologic specimen: organ-confined disease, negative margins",
      "PSA undetectable (< 0.1) at 6 weeks post-surgery",
      "Pelvic floor physiotherapy for continence recovery",
      "PSA monitoring every 3–6 months",
    ],
    totalCycles: 0,
    radiationIncluded: false,
    treatmentDurationMonths: 1,
    interimPETResult: "Pathologically organ-confined, negative margins",
    endOfTreatmentResult: "Undetectable PSA — biochemical remission",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 7,
    currentStatus: "7 years with undetectable PSA. Fully continent. Active retired life.",
    publishedYear: 2018,
    journalRef: "Journal of Urology — outcomes of robotic prostatectomy for Grade Group 2",
    patientNote: "His cancer was found from a routine PSA test — no symptoms at all. Robotic surgery, 2 nights in hospital, home in time for his golf weekend (eventually). PSA has been undetectable for 7 years. He says catching it early made all the difference.",
  },
  {
    id: "PC-002",
    ageAtDiagnosis: 68,
    ageGroup: "senior",
    gender: "M",
    cancerType: "prostate",
    stage: "Stage 3A",
    subtype: "A",
    location: "United Kingdom",
    presentingSymptom: "PSA of 18, urinary frequency, diagnosed after TRUS biopsy",
    diagnosisMethod: "12-core TRUS biopsy (Gleason 8 = Grade Group 4)",
    timeFromSymptomToDiagnosis: "10 weeks",
    treatmentProtocol: "External beam radiation (EBRT 78 Gy) + 24 months ADT (hormonal therapy)",
    treatmentDetails: [
      "78 Gy EBRT in 39 fractions over 8 weeks",
      "Concurrent LHRH agonist (leuprolide) — 24 months",
      "PSA nadir reached at 18 months",
      "Treatment side effects managed: fatigue, hot flashes, reduced libido — largely resolved after ADT stopped",
    ],
    totalCycles: 0,
    radiationIncluded: true,
    treatmentDurationMonths: 10,
    interimPETResult: "PSA declining appropriately on ADT",
    endOfTreatmentResult: "PSA < 0.5 at 2 years",
    outcome: "ongoing remission",
    timeToRemissionMonths: 18,
    followUpYears: 5,
    currentStatus: "5 years — PSA 0.3, stable. Off ADT for 3 years. Active.",
    publishedYear: 2019,
    journalRef: "Lancet Oncology — DART 01/05 GETUG trial",
    patientNote: "High-risk prostate cancer treated with radiation + hormonal therapy. After completing hormonal treatment, he bounced back — energy returned, side effects resolved. 5 years later PSA remains near undetectable.",
  },

  // ===== COLORECTAL CANCER =====
  {
    id: "CRC-001",
    ageAtDiagnosis: 48,
    ageGroup: "adult",
    gender: "M",
    cancerType: "colorectal",
    stage: "Stage 2A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Blood in stool noticed for 6 weeks, attributed to hemorrhoids initially",
    diagnosisMethod: "Colonoscopy + biopsy (T3N0M0 sigmoid adenocarcinoma), CT staging",
    timeFromSymptomToDiagnosis: "10 weeks",
    treatmentProtocol: "Laparoscopic sigmoid colectomy (no adjuvant chemo — low-risk Stage 2A)",
    treatmentDetails: [
      "Laparoscopic sigmoid colectomy — 4-night hospital stay",
      "Pathology: T3N0 — no lymph node involvement, clear margins",
      "MSI-high (microsatellite instability) — good prognosis marker",
      "No adjuvant chemotherapy recommended (low-risk Stage 2A, MSI-H)",
      "Colonoscopy surveillance every 1–3 years",
    ],
    totalCycles: 0,
    radiationIncluded: false,
    treatmentDurationMonths: 1,
    interimPETResult: "Clear margins, node-negative at surgery",
    endOfTreatmentResult: "No evidence of disease",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 6,
    currentStatus: "6 years disease-free. Annual CEA normal. Follow-up colonoscopy clean.",
    publishedYear: 2019,
    journalRef: "JNCI — stage 2 colorectal outcomes, MSI-H cohort",
    patientNote: "He ignored the blood in stool for 6 weeks thinking it was hemorrhoids. His GP sent him for colonoscopy which found the cancer early — still at Stage 2, not spread to lymph nodes. Laparoscopic surgery, home in 4 days, back to work in 3 weeks. 6 years clear.",
  },
  {
    id: "CRC-002",
    ageAtDiagnosis: 52,
    ageGroup: "adult",
    gender: "F",
    cancerType: "colorectal",
    stage: "Stage 3B",
    subtype: "A",
    location: "Canada",
    presentingSymptom: "Change in bowel habits, fatigue, 3 kg weight loss over 2 months",
    diagnosisMethod: "Colonoscopy biopsy (T3N2M0), CT + MRI staging",
    timeFromSymptomToDiagnosis: "8 weeks",
    treatmentProtocol: "Surgical resection (right hemicolectomy) + 6 months FOLFOX chemotherapy",
    treatmentDetails: [
      "Right hemicolectomy — open surgery",
      "4 of 18 lymph nodes positive (pN2 = Stage 3B)",
      "Adjuvant chemotherapy: 12 cycles FOLFOX (oxaliplatin + fluorouracil)",
      "Neuropathy from oxaliplatin — managed, resolved largely after completing chemo",
    ],
    totalCycles: 12,
    radiationIncluded: false,
    treatmentDurationMonths: 7,
    interimPETResult: "Post-surgical CEA normalizing",
    endOfTreatmentResult: "No evidence of disease — CEA normal",
    outcome: "complete remission",
    timeToRemissionMonths: 8,
    followUpYears: 5,
    currentStatus: "5 years disease-free. CEA normal. Surveillance colonoscopy clear. Mild residual neuropathy in feet.",
    publishedYear: 2020,
    journalRef: "MOSAIC trial long-term follow-up — FOLFOX stage 3 colon cancer",
    patientNote: "Stage 3B is more intensive — surgery plus 6 months of chemo. The oxaliplatin caused tingling in her fingers and feet (neuropathy). She got through it. 5 years later, cancer-free. The neuropathy is mild and still fading.",
  },

  // ===== MELANOMA =====
  {
    id: "MEL-001",
    ageAtDiagnosis: 35,
    ageGroup: "adult",
    gender: "M",
    cancerType: "melanoma",
    stage: "Stage 2B",
    subtype: "A",
    location: "Australia",
    presentingSymptom: "Changing mole on back — darker, irregular border, 2.8mm Breslow thickness",
    diagnosisMethod: "Excisional biopsy + wide local excision + SLNB",
    timeFromSymptomToDiagnosis: "4 weeks",
    treatmentProtocol: "Wide local excision + SLNB + adjuvant pembrolizumab (1 year)",
    treatmentDetails: [
      "Wide local excision with 2 cm margins",
      "Sentinel lymph node biopsy — negative",
      "Stage 2B: high-risk features — eligible for adjuvant immunotherapy",
      "12 months adjuvant pembrolizumab (KEYNOTE-716)",
      "Tolerated well — mild fatigue, thyroid managed with levothyroxine",
    ],
    totalCycles: 18,
    radiationIncluded: false,
    treatmentDurationMonths: 12,
    interimPETResult: "No distant disease on staging PET",
    endOfTreatmentResult: "No evidence of disease",
    outcome: "complete remission",
    timeToRemissionMonths: 1,
    followUpYears: 3,
    currentStatus: "3 years disease-free. 6-monthly skin checks. On thyroid replacement (immunotherapy side effect).",
    publishedYear: 2022,
    journalRef: "NEJM — KEYNOTE-716, pembrolizumab adjuvant Stage 2B melanoma",
    patientNote: "He had the mole on his back for years but it changed. His dermatologist biopsied it immediately. Stage 2B — high risk of recurrence — so he got a year of immunotherapy. The only lasting side effect was thyroid (easily managed with a daily pill). 3 years clear.",
  },
  {
    id: "MEL-002",
    ageAtDiagnosis: 47,
    ageGroup: "adult",
    gender: "F",
    cancerType: "melanoma",
    stage: "Stage 3C",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Melanoma on leg plus palpable inguinal lymph nodes",
    diagnosisMethod: "Biopsy + lymph node FNA + PET-CT (BRAF V600E mutation)",
    timeFromSymptomToDiagnosis: "6 weeks",
    treatmentProtocol: "Surgical resection + lymph node dissection + adjuvant nivolumab + ipilimumab (ipi/nivo)",
    treatmentDetails: [
      "Excision of primary + inguinal lymph node dissection",
      "BRAF V600E positive — eligible for targeted therapy option",
      "Chose adjuvant immunotherapy (ipi/nivo): 4 doses combination, then nivolumab maintenance 1 year",
      "Immune-related adverse events: colitis (managed with steroids) — resolved",
    ],
    totalCycles: 16,
    radiationIncluded: false,
    treatmentDurationMonths: 15,
    interimPETResult: "No distant metastases",
    endOfTreatmentResult: "Complete remission confirmed on PET",
    outcome: "complete remission",
    timeToRemissionMonths: 6,
    followUpYears: 4,
    currentStatus: "4 years disease-free. Quarterly surveillance. Colitis resolved.",
    publishedYear: 2021,
    journalRef: "NEJM — CheckMate 238 / CA209-238 adjuvant nivolumab melanoma",
    patientNote: "Stage 3C melanoma was once very difficult to treat. Immunotherapy changed everything. She had a tough 3 months with colitis from the immune treatment — managed with steroids — then she recovered. 4 years disease-free.",
  },

  // ===== THYROID CANCER =====
  {
    id: "TC-001",
    ageAtDiagnosis: 31,
    ageGroup: "adult",
    gender: "F",
    cancerType: "thyroid",
    stage: "Stage 1",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Thyroid nodule found incidentally on neck ultrasound for unrelated issue",
    diagnosisMethod: "Fine needle aspiration (papillary thyroid carcinoma, 1.2 cm)",
    timeFromSymptomToDiagnosis: "6 weeks",
    treatmentProtocol: "Hemithyroidectomy (lobectomy) — no RAI needed",
    treatmentDetails: [
      "Right thyroid lobectomy — same-day/overnight surgery",
      "Final pathology: papillary thyroid microcarcinoma, no vascular invasion, negative margins",
      "No radioactive iodine needed (low-risk Stage 1 < 4 cm, no extrathyroidal extension)",
      "Levothyroxine replacement at suppressive dose",
      "Annual neck ultrasound + Tg monitoring",
    ],
    totalCycles: 0,
    radiationIncluded: false,
    treatmentDurationMonths: 1,
    interimPETResult: "Undetectable Tg post-operatively",
    endOfTreatmentResult: "No evidence of disease",
    outcome: "complete remission",
    timeToRemissionMonths: 1,
    followUpYears: 9,
    currentStatus: "9 years disease-free. Takes a daily thyroid pill. Ultrasounds normal.",
    publishedYear: 2016,
    journalRef: "Thyroid — ATA guidelines outcomes for low-risk papillary thyroid cancer",
    patientNote: "Thyroid cancer Stage 1 has a near 100% 10-year survival rate. She had half her thyroid removed as a day surgery procedure, takes a daily pill, and has been cancer-free for 9 years. Her doctors call it 'the best cancer to have if you have to have cancer.'",
  },

  // ===== CERVICAL CANCER =====
  {
    id: "CC-001",
    ageAtDiagnosis: 34,
    ageGroup: "adult",
    gender: "F",
    cancerType: "cervical",
    stage: "Stage 1B1",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Abnormal Pap smear (high-grade lesion) → colposcopy and biopsy",
    diagnosisMethod: "LLETZ biopsy (squamous cell carcinoma 1.5 cm), MRI pelvis",
    timeFromSymptomToDiagnosis: "12 weeks",
    treatmentProtocol: "Radical hysterectomy + pelvic lymph node dissection",
    treatmentDetails: [
      "Robotic-assisted radical hysterectomy",
      "Bilateral pelvic lymph node dissection — all negative",
      "Clear surgical margins — organ-confined disease",
      "Ovaries preserved (bilateral salpingo-oophorectomy not required)",
      "No adjuvant radiation needed (negative nodes, clear margins)",
    ],
    totalCycles: 0,
    radiationIncluded: false,
    treatmentDurationMonths: 1,
    interimPETResult: "No lymph node involvement — organ-confined",
    endOfTreatmentResult: "No evidence of disease",
    outcome: "complete remission",
    timeToRemissionMonths: 2,
    followUpYears: 6,
    currentStatus: "6 years disease-free. Annual follow-up clear. Ovaries preserved — no premature menopause.",
    publishedYear: 2019,
    journalRef: "Gynecologic Oncology — robotic radical hysterectomy outcomes Stage 1B1",
    patientNote: "Found through a routine Pap smear — exactly why they matter. Stage 1B1 treated with surgery alone. She kept her ovaries so no forced early menopause. 6 years clear — she credits the Pap smear for saving her life.",
  },

  // ===== OVARIAN CANCER =====
  {
    id: "OC-001",
    ageAtDiagnosis: 56,
    ageGroup: "adult",
    gender: "F",
    cancerType: "ovarian",
    stage: "Stage 3C",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Abdominal bloating, pelvic pressure for 3 months, CA-125 elevated (890)",
    diagnosisMethod: "CT abdomen/pelvis + surgical staging (high-grade serous ovarian carcinoma)",
    timeFromSymptomToDiagnosis: "10 weeks",
    treatmentProtocol: "Primary debulking surgery + 6 cycles carboplatin/paclitaxel + olaparib maintenance (BRCA1+)",
    treatmentDetails: [
      "Optimal cytoreductive surgery — no visible residual disease",
      "6 cycles carboplatin + paclitaxel — completed",
      "BRCA1 mutation identified — eligible for PARP inhibitor maintenance",
      "2 years olaparib (Lynparza) maintenance — SOLO-1 protocol",
      "CA-125 normalized after 3 cycles",
    ],
    totalCycles: 6,
    radiationIncluded: false,
    treatmentDurationMonths: 30,
    interimPETResult: "CA-125 normalized, imaging clear after 6 cycles",
    endOfTreatmentResult: "Complete clinical remission",
    outcome: "ongoing remission",
    timeToRemissionMonths: 8,
    followUpYears: 5,
    currentStatus: "5 years progression-free (exceptional for Stage 3C BRCA+). PARP inhibitor changed her prognosis.",
    publishedYear: 2021,
    journalRef: "NEJM — SOLO-1 trial, olaparib maintenance BRCA-mutated ovarian cancer",
    patientNote: "Stage 3C ovarian cancer used to have a very poor prognosis. BRCA mutation testing changed everything — she was eligible for olaparib maintenance. 5 years progression-free is remarkable for Stage 3C. She calls PARP inhibitors 'the drug that gave me my life back.'",
  },

  // ===== BRAIN TUMOR =====
  {
    id: "BT-001",
    ageAtDiagnosis: 29,
    ageGroup: "adult",
    gender: "M",
    cancerType: "brain",
    stage: "Grade 2",
    subtype: "A",
    location: "United States",
    presentingSymptom: "New-onset seizure at work, no prior symptoms",
    diagnosisMethod: "MRI brain + surgical biopsy (IDH-mutant astrocytoma Grade 2)",
    timeFromSymptomToDiagnosis: "4 weeks",
    treatmentProtocol: "Maximal safe resection + watch-and-wait (low-grade protocol)",
    treatmentDetails: [
      "Awake craniotomy — maximal safe resection (95% tumor removed)",
      "IDH mutation confirmed — good prognostic marker for low-grade glioma",
      "Post-operative: anti-epileptic medication for seizure prevention",
      "Active surveillance MRI every 3–6 months",
      "Radiation/chemo deferred — low-risk features, young patient",
    ],
    totalCycles: 0,
    radiationIncluded: false,
    treatmentDurationMonths: 2,
    interimPETResult: "Near-total resection on post-op MRI",
    endOfTreatmentResult: "No progression on 3-year surveillance",
    outcome: "ongoing remission",
    timeToRemissionMonths: 3,
    followUpYears: 3,
    currentStatus: "3 years stable on surveillance. No seizures on medication. Working full-time. MRIs stable.",
    publishedYear: 2020,
    journalRef: "NEJM — Management of IDH-mutant low-grade glioma, EORTC outcomes",
    patientNote: "A seizure out of nowhere at age 29. Awake brain surgery (he was talking to the team during the procedure to protect language areas). IDH mutation is a positive marker. 3 years of stable MRIs. He's back at work and says the surgery 'was weirdly fascinating.'",
  },

  // ===== KIDNEY CANCER =====
  {
    id: "KC-001",
    ageAtDiagnosis: 61,
    ageGroup: "adult",
    gender: "M",
    cancerType: "kidney",
    stage: "Stage 1A",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Incidental finding on abdominal ultrasound for unrelated gallstones — 2.8 cm renal mass",
    diagnosisMethod: "CT scan (clear cell RCC radiological diagnosis), confirmed post-op",
    timeFromSymptomToDiagnosis: "6 weeks",
    treatmentProtocol: "Robotic partial nephrectomy (nephron-sparing surgery)",
    treatmentDetails: [
      "Robotic partial nephrectomy — preserved 95% of kidney function",
      "Pathology confirmed clear cell RCC, organ-confined, Grade 2",
      "No adjuvant therapy needed for Stage 1A RCC",
      "CT scan surveillance every 6 months for 2 years, then annually",
    ],
    totalCycles: 0,
    radiationIncluded: false,
    treatmentDurationMonths: 1,
    interimPETResult: "Pathologically organ-confined, Grade 2, negative margins",
    endOfTreatmentResult: "No evidence of disease",
    outcome: "complete remission",
    timeToRemissionMonths: 1,
    followUpYears: 7,
    currentStatus: "7 years disease-free. Kidney function normal. Annual CT scan surveillance.",
    publishedYear: 2017,
    journalRef: "European Urology — partial vs radical nephrectomy Stage 1 RCC outcomes",
    patientNote: "Found by accident when they were looking at his gallstones. He had no symptoms. Robotic partial nephrectomy — home in 2 days, his kidney function is virtually unchanged. 7 years disease-free. He calls it 'the gallstone that saved my life.'",
  },

  // ===== BLADDER CANCER =====
  {
    id: "BLC-001",
    ageAtDiagnosis: 66,
    ageGroup: "senior",
    gender: "M",
    cancerType: "bladder",
    stage: "Stage 1",
    subtype: "A",
    location: "United Kingdom",
    presentingSymptom: "Painless visible blood in urine (haematuria) for 2 weeks",
    diagnosisMethod: "Flexible cystoscopy + TURBT biopsy (Ta high-grade urothelial carcinoma)",
    timeFromSymptomToDiagnosis: "4 weeks",
    treatmentProtocol: "TURBT (transurethral resection) + intravesical BCG immunotherapy",
    treatmentDetails: [
      "TURBT — endoscopic removal of bladder tumor (day procedure)",
      "Re-TURBT at 6 weeks confirmed clear",
      "BCG intravesical immunotherapy: 6-week induction + 3-year maintenance",
      "Regular cystoscopy surveillance every 3 months initially",
    ],
    totalCycles: 0,
    radiationIncluded: false,
    treatmentDurationMonths: 6,
    interimPETResult: "Clear re-TURBT — no residual tumor",
    endOfTreatmentResult: "Complete response",
    outcome: "complete remission",
    timeToRemissionMonths: 3,
    followUpYears: 6,
    currentStatus: "6 years disease-free. Cystoscopy every 12 months — consistently clear.",
    publishedYear: 2018,
    journalRef: "European Urology — BCG vs chemotherapy non-muscle-invasive bladder cancer",
    patientNote: "Painless blood in urine — always get it checked. His endoscopic surgery was day procedure. BCG immunotherapy is a proven treatment for bladder cancer. 6 years of clear cystoscopies.",
  },

  // ===== CLL (adult leukemia) =====
  {
    id: "CLL-001",
    ageAtDiagnosis: 72,
    ageGroup: "senior",
    gender: "M",
    cancerType: "cll",
    stage: "Stage 2",
    subtype: "A",
    location: "United States",
    presentingSymptom: "Absolute lymphocyte count 28,000 found on routine CBC — asymptomatic",
    diagnosisMethod: "Flow cytometry (CLL immunophenotype), FISH/cytogenetics (del 13q — favorable)",
    timeFromSymptomToDiagnosis: "3 weeks",
    treatmentProtocol: "Watch and wait → venetoclax + obinutuzumab (CLL14 protocol) when progression",
    treatmentDetails: [
      "Watch and wait for 2 years (asymptomatic, indolent CLL)",
      "Started treatment at progression: venetoclax + obinutuzumab — 12 months fixed-duration",
      "Complete remission with undetectable MRD after 12 months",
      "Fixed-duration — treatment stopped, ongoing surveillance",
    ],
    totalCycles: 12,
    radiationIncluded: false,
    treatmentDurationMonths: 12,
    interimPETResult: "Undetectable MRD (minimal residual disease) at end of treatment",
    endOfTreatmentResult: "Complete remission, uMRD",
    outcome: "complete remission",
    timeToRemissionMonths: 12,
    followUpYears: 3,
    currentStatus: "3 years post-treatment. MRD negative. Blood counts normal. Active retirement.",
    publishedYear: 2022,
    journalRef: "NEJM — CLL14 trial, venetoclax + obinutuzumab vs chlorambucil",
    patientNote: "CLL is often slow-growing. He watched and waited for 2 years, then when treatment was needed, venetoclax was transformative. Fixed-duration 12 months, then treatment stopped. Complete remission. Modern CLL therapy is a remarkable success story.",
  },
];

export function getSimilarCases(
  cancerType: string,
  stage: string,
  ageGroup: string,
  subtype?: string
): Array<Case & { similarityScore: number; matchReasons: string[] }> {
  const scored = cases.map((c) => {
    let score = 0;
    const reasons: string[] = [];

    // Cancer type match (40 points)
    if (c.cancerType === cancerType) {
      score += 40;
      reasons.push(`Same cancer type (${c.cancerType === "hodgkin" ? "Hodgkin's Lymphoma" : c.cancerType.toUpperCase()})`);
    }

    // Stage match (30 points)
    const normalizedInputStage = stage.replace("Stage ", "").trim();
    const normalizedCaseStage = c.stage.replace("Stage ", "").trim();

    if (normalizedCaseStage === normalizedInputStage) {
      score += 30;
      reasons.push(`Exact same stage (${c.stage})`);
    } else if (
      normalizedCaseStage.charAt(0) === normalizedInputStage.charAt(0)
    ) {
      score += 18;
      reasons.push(`Similar stage group (${c.stage} vs ${stage})`);
    } else if (
      Math.abs(
        parseInt(normalizedCaseStage.charAt(0)) -
          parseInt(normalizedInputStage.charAt(0))
      ) === 1
    ) {
      score += 8;
      reasons.push(`Adjacent stage (${c.stage})`);
    }

    // Age group match (20 points)
    if (c.ageGroup === ageGroup) {
      score += 20;
      reasons.push(`Same age group (${ageGroup})`);
    } else if (
      (ageGroup === "child" && c.ageGroup === "teen") ||
      (ageGroup === "teen" && c.ageGroup === "child")
    ) {
      score += 10;
      reasons.push("Similar pediatric age range");
    }

    // Subtype match (10 points)
    if (subtype && c.subtype !== "N/A") {
      if (c.subtype === subtype) {
        score += 10;
        reasons.push(`Same subtype (Type ${subtype} — no B-symptoms)`);
      }
    }

    return { ...c, similarityScore: score, matchReasons: reasons };
  });

  return scored
    .filter((c) => c.similarityScore >= 40) // must at least match cancer type
    .sort((a, b) => b.similarityScore - a.similarityScore)
    .slice(0, 3);
}
